---
title: Reconstructed Arguments
format:
  html:
    toc: true
---
# GM-1: Free Public Access to TWONs {#sec-free-access}

## Pro-Arguments Free Public Access {#sec-pro-free-access}

### Debunking Pro-Argumentation GM-1

::::: {.panel-tabset}

#### Idea of the Argumentation

This argumentative strategy aims to debunk the prima-facie objections to the free access governance of TWONs. In our case that means that this strategy argues that the identified risks from the GM-1 will not be materialized. 

#### Map of Arguments

```{dot}
//| fig-cap: "Argument map of debunking the reasons against free public access to TWONs"
//| file: ./twon-analysis/gm1-pro-debunking.argdown.dot
```

#### Reconstruction

::: {.callout-note collapse="true" icon="false"}

#### Debunking Pro-Argument: Risks from Free Public Access are Insignificant

(1) **[Benefits from Free Access are Significant]** It is reasonable to expect that an unrestricted access to TWONs will bring about the following morally significant benefits:
    * (B-1-1) Increase in social welfare (in an amount of ∆ SW(GM-1));
    * (B-1-2) Improvement of individual quality of life (in an amount of ∆ QoL (GM-1));
    * (B-2-2) Respect of individual autonomy;
    * (B-2-3) Increase in deliberative quality;
    * (B-2-4) Additional knowledge addressing existing injustices.
(2) **[Risks from Free Access are Insignificant]** It is reasonable to expect that an unrestricted access to TWONs will not materialize the projected risks to a significant amount. 
(3) **[Decision Rule]** A means M should be used if the following conditions are met:
    (i) it is reasonable to expect that use of M brings about significant benefits B and
    (ii) the expected drawbacks from M’s use are insignificant and
    (iii) for all other available means M_alt for which it is reasonable to expect that they realize at least B it is also reasonable to expect that they bring about moral drawbacks in a significant amount.
(4) **[No-Alternatives to TWONs without Drawbacks]**: According to the best available knowledge, there is no other means by which the benefits (B-1-1,...,B-3) could be realized without significant drawbacks.

----

(5) **[Conclusion]** Access to TWONs ought to be unrestricted.
:::

::: {.callout-warning icon="false" collapse="true"}

#### Additional claims to which a proponent of the Debunking-Pro-Argument is committed

Premise (2) in the Debunking-Pro-Argument implies the following claims:

| **[Contra R-1-2]**: It is unreasonable to expect that a free public access to TWONs will lead to a significant reduction in individual quality of life due to misuse of personal data.
| **[Contra R-2-1]**: It is unreasonable to expect that a free public access to TWONs will increase violations of the right to informational privacy.
| **[Contra R-2-2]**: It is unreasonable to expect that a free access to TWONs will intesinfy undermining of individual autonomy on onlice social networks. 
| **[Contra R-2-3]**: It is unreasonable to expect that a free access to TWONs will lead to a collapse of institutions necessary for democratic governance.
| **[Contra R-2-4]**: It is unreasonable to expect that a free access to TWONs will reinforce the existing inequalities in financial and power relations at the national and global level.
:::

:::::

### Balancing Pro-Argumentation GM-1

::::: {.panel-tabset}

#### Idea of the Argumentation
This argumentative strategy accepts that a free public access to TWONs will have both significant benefits and risks. The pro-balancing argumentation argues that the benefits of free public access to TWONs are so important that it is morally legitimate to accept the risks of this mode of governance. 

#### Map of Arguments

```{=html}
<iframe src="./twon-analysis/gm1-pro-balancing.html" width="100%" height="500px"></iframe>
```

#### Reconstruction

::: {.callout-note collapse="true" icon="false"}

#### Balancing Pro-Argument: Benefits from Free Public Access Outweigh the Risks

(1) **Benefits from Free Access** It is reasonable to expect that an unrestricted access to TWONs will bring about the following morally significant benefits:
    * (B-1-1) Increase in social welfare (in an amount of ∆ SW(GM-1));
    * (B-1-2) Improvement of individual quality of life (in an amount of ∆ QoL (GM-1));
    * (B-2-2) Respect of individual autonomy;
    * (B-2-3) Increase in deliberative quality;
    * (B-2-4) Additional knowledge addressing existing injustices.
(2) **Risks from Free Access**: It is reasonable to expect that an unrestricted access to TWONs will involve moral drawbacks in a significant amount:
    * (R-1-2) Deterioration of individual quality of life;
    * (R-2-1) Vioalations of the right to informational privacy;
    * (R-2-2) Undermining of individual autonomy;
    * (R-2-3) Collapse of democratic institutions;
    * (R-2-4) Harms to future generations;
    * (R-2-5) Reinforcement of existing inequalities.
(3) **Decision Rule: Protection of Democracy Outweighs the Risks**: Protection of democracy and of individual autonomy have such a high moral importance that it holds:
    * If there is a means M for which it is reasonable to expect that the society obtains the ability to prevent that democratic institutions collapse and to protect individual autonomy and whose deployment involves the possibility that it leads to a collapse of democratic institutions (R-2-3), undermination of individual autonomy (R-2-2) and involves further possible moral drawbacks R-1-2,R-2-1, R-2-4, R-2-5.
    * and for all other available means M_alt for which it is reasonable to expect that they protect democratic institutions it is reasonable to expect that they will involve moral drawbacks higher than (R-1-2,..., R-2-5)
    * then M ought to be realized.
(4) **No Alternatives to GM-1 with Smaller Risks**: According to the best available knowledge, all alternative ways to protect democratic institutions involve higher moral risks than (R-1-2, R-2-1. R-2-2, R-2-4, R-2-5).

----

(5) **Conclusion**: Access to TWONs ought to be unrestricted.
:::

::: {.callout-warning icon="false" collapse="true"}

#### Additional claims to which a proponent of the Balancing-Pro-Argument is committed

| Premise (4) **[No Alteratives to GM-1 with Smaller Risks]**: There are no alternative ways to protect democratic institutions and individual autonomy than providing a free public access to TWONs.

Premise (4) implies:
  
  * the more restricitive modes of governance of TWONs (e.g. GM-2 and GM-3) are not realizable.

Premise (3) **[Decision Rule]** is an instance of a more general claim:
  
  * If  M provides an effective means to avoid that a thread that p (i.e. the possibility that p with p leading to a high negative impact) will be realized and realization of M involves the thread that p, and there are no other means by which the thread that p can be effectively avoided, M ought to be realized.
    * this general claim contains a risk-prone decision rule which needs an ethical justification. 

:::

:::::

## Contra-Arguments Free Public Access {#sec-contra-free-access}

### Debunking Benefits from GM-1 Argumentation

::: {.panel-tabset}
#### Idea of the Argumentation
This argumentative strategy aims to debunk the prima-facie reasons for the free access governance of TWONs. In our case that means that this strategy argues that the expected benefits from the GM-1 will not be materialized (or will be insignificant).

#### Map of Arguments


```{=html}
<iframe src="./twon-analysis/gm1-contra-debunking.html" width="100%" height="500px"></iframe>
```

#### Reconstruction of Arguments

::: {.callout-note icon="false" collapse="true"}
#### Debunking Contra-Argument: Benefits from Free Public Access are insignificant

(1) **Benefits from Free Access** It is unreasonable to expect any benefits from an unrestricted access to TWONs.
(2) **Risks from Free Access**: It is reasonable to expect that an unrestricted access to TWONs will involve moral drawbacks in a significant amount:
    * (R-1-2) Deterioration of individual quality of life;
    * (R-2-1) Vioalations of the right to informational privacy;
    * (R-2-2) Undermining of individual autonomy;
    * (R-2-3) Collapse of democratic institutions;
    * (R-2-4) Harms to future generations;
    * (R-2-5) Reinforcement of existing inequalities.
(3) **Decision Rule**: If it is reasonable to expect that a means M jeopardizes moral rights to a morally significant degree and it is reasonable to expect that M will not realize morally significant benefits, it is morally not allowed to realize M.

----

(4) **Conclusion**: A society ought not to allow an unrestricted public access to TWONs.
:::

::: {.callout-warning icon="false" collapse="true"}
#### Additional claims to which a proponent of the Debunking-Contra-Argument is committed

Premise (1) in the Debunking-Contra-Argument implies the following claims:

| **[Contra B-1-1]**: It is unreasonable to expect that a free access to TWONs will increase social welfare (in an amount of ∆ SW(GM-1)).
| **[Contra B-1-2]**: It is unreasonable to expect that a free access to TWONs will improve individual quality of life (in an amount of ∆ QoL (GM-1)).
| **[Contra B-2-2]**: It is unreasonable to expect that a free access to TWONs will enable a society to protect individual autonomy on OSNs.
| **[Contra B-2-3]**: It is unreasonable to expect that a free access to TWONs will protect democratic institutions or increase deliberative quality in democratic societies;
| **[Contra B-2-4]**: It is unreasonable to expect that a free access to TWONs will lead to additional knowledge addressing existing injustices.
:::
:::

### Balancing Prima facie Reasons against GM-1

::::: {.panel-tabset}
#### Idea of the Argumentation

This argumentative strategy accepts that a free public access to TWONs will have both significant benefits and risks. The contra-balancing argumentation contains two arguments:

* Precautionary Argument argues that the possible drawbacks from the free access to TWONs are so significant that they should not be accepted regardeless of its benefits.

* The Availability-of-Alternatives Argument argues that there are alternatives to an unrestricted use of TWONs which realize the same benefits with lower risks.

#### Maps of Arguments

```{=html}
<iframe src="./twon-analysis/gm1-contra-balancing.html" width="100%" height="500px"></iframe>
```

#### Reconstruction of Arguments
::: {.callout-note collapse="true" icon="false"}

#### Argument from Precaution

(1) **Threshold Precautionary Principle** If it is seriously possible that the use of a means M will lead to a violation of moral rights beyond a threshold of what is morally acceptable (R_min), then a society ought not to allow M to be realized, regardless of its expected benefits.
(2) **Democracy-Thread from Free Access**: It is reasonable to expect that an unrestricted access to TWONs will lead to a collapse of democratic institutions (R-2-3).
(3) Collapse of democratic governance is an outcome beyond a threshold of what is morally acceptable.

----

(5) **Conclusion**: A society ought not to allow an unrestricted public access to TWONs.
:::

::: {.callout-note collapse="true" icon="false"}

#### Argument from the Availability of Alternatives

(1) **Benefits from Free Access** It is reasonable to expect that an unrestricted access to TWONs will bring about the following morally significant benefits:
    * (B-2-2) Respect of individual autonomy;
    * (B-2-3) Increase in deliberative quality;
    * (B-2-4) Additional knowledge addressing existing injustices.
(2) **Risks from Free Access**: It is reasonable to expect that an unrestricted access to TWONs will involve moral drawbacks in a significant amount:
    * (R-2-1) Vioalations of the right to informational privacy;
    * (R-2-2) Undermining of individual autonomy;
    * (R-2-3) Collapse of democratic institutions;
    * (R-2-4) Harms to future generations;
    * (R-2-5) Reinforcement of existing inequalities.
(3) **Alternatives to GM-1 with Lower Risks** There are means for which it is reasonable to expect that they realize the benefits (B-2-2), (B-2-3), and (B-2-4) with lower risks than (R-2-1),...,(R-2-5).
(4) **Least-Cost Means should be chosen**: Among the means M_1,...,M_n that all achieve the same goal g, the means M_i should be chosen that has the least drawbacks.

----

(5) **Conclusion**: A society ought not to allow an unrestricted public access to TWONs.
:::
<!--
::: {.callout-warning icon="false" collapse="true"}

#### Additional claims to which a proponent of the Balancing-Contra-Arguments is committed

| Premise (3) **[Alteratives to GM-1 with Lower Risks]**: There are no alternative ways to protect democratic institutions and individual autonomy than providing a free public access to TWONs.
:::
-->
:::::

# GM-2 Vetted Researchers Access Only {#sec-researchers-access}

## Pro-Arguments GM-2 {#sec-pro-researchers-access}
### Debunking Prima facie Reasons against GM-2

::: {.panel-tabset}
#### Maps of Arguments

#### Reconstruction of Arguments
tba
:::

### Balancing Pro-Argument GM-2

::: {.panel-tabset}
#### Maps of Arguments

#### Reconstruction of Arguments
tba
:::

## Contra-Arguments GM-2 {#sec-contra-researchers-access}
### Debunking Prima facie Reasons for GM-2

::: {.panel-tabset}
#### Maps of Arguments

#### Reconstruction of Arguments
tba
:::


### Balancing Reasons against GM-2

::: {.panel-tabset}
#### Maps of Arguments

#### Reconstruction of Arguments
tba
:::

# GM-3 Judicial Authority {#sec-judicial}

## Pro-Arguments GM-3 {#sec-pro-judicial}
### Debunking Pro-Argument GM-3
::: {.panel-tabset}
#### Maps of Arguments

#### Reconstruction of Arguments
tba
:::

### Balancing Pro-Argument GM-3
::: {.panel-tabset}
#### Maps of Arguments

#### Reconstruction of Arguments
tba
:::

## Contra-Arguments GM-3 {#sec-contra-judicial}
### Debunking Contra-Argument GM-3
::: {.panel-tabset}
#### Maps of Arguments

#### Reconstruction of Arguments
tba
:::


### Balancing Contra-Argument GM-3
::: {.panel-tabset}
#### Maps of Arguments

#### Reconstruction of Arguments
tba
:::