project:
  type: website
  output-dir: docs

website:
  title: "TWON-Website-Mockup"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Arg-Anal-Method.qmd
        text: Methods
      - href: output.qmd
        text: Outcomes
    right:
      - about.qmd
    collapse: true

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



