---
title: "Methodology of Argumentation Analysis"
---

## Example: Should I Lie or Should I not?

Suppose, you are in a situation in which a lie would prevent a bad outcome. Should you lie or should you risk the bad outcome? -- Here is a story:^[Feel free to think another story in which a lie would prevent a bad outcome!]

* Your friend asks you to tell her when the latest public transport connection leaves by which she will be at a meeting place at 2 o'clock.
  * She must be at a place in another part of the city for a highly important meeting. She is unfamiliar with the city and needs your advise on how to get to the meeting place. 
* You know:
  * The last connection that will bring her on time leaves at 1.30. The next one leaves 30 min later -- meaning that if she misses the 1.30 connection, she will miss the meeting. The one earlier leaves at 1 o'clock meaning that she will have waiting time of about 30 minutes at the meeting place.
  * Your friend has a tendency to miss the connections she intends to catch. She often sees the train just driving away from the station.
* Your options:
  * **Tell the truth!**: You tell your friend that the last train leaves at 1.30 and that the next departs only 30 minutes later implying that she will miss the meeting if she misses the train. You add that you strongly recommend her to take a connection earlier.
  * **Lie!**: You tell your friend that the latest public transport connection leaves at 1 o'clock and will bring her to the meeting place about 30 minutes before the meeting starts.
  * For simplicity, let us assume that there are no other options for you^[In reality, there will be further relevant options, but let us assume here that they do not exist: </br>* telling the truth and than reminding your friend to leave on time for the last train; </br>* considering another means of transportation (e.g. taxi) for the case the public transport option will be missed; </br>* nudging your friend: presenting both options in a way that your friend finds the earlier one more attractive.]
* You must decide: to stick to truth or to lie?

## Argumentation Analysis: it's Idea

<!--
```{mermaid}
/*flowchart TD
/*C1[Pro-Truth Sticking]-> A(Trumping Arguments) & B(Balancing Arguments) & D(Debunking Arguments)
/*C2[Pro-Lying]-> A(Trumping Arguments) & B(Balancing Arguments) & D(Debunking Arguments)
```
-->



```{dot}
//| fig-cap: structure-lying-truth
//| file: ./Graphics/Truth-Lying-Decision-Problem.dot 
```

| | **Argumentation Analysis structures the process of weighing reasons** | |
|---|:--------:|---|

* You must decide which option for action to choose: "T!: sticking to truth" or "L!: lying".
* There are reasons for both options for action.
* Argumentation Analysis supports you in clarifying the process of wheighing.


## Process of the Argumentation Analysis

::: {.callout-caution icon="false" collapse="true"}
### Step 0: Specification of the available options for action
As a prerequisite of an argumentation analysis, you need to identify all the available options for action in the case your are interested in. </br>Here, we [have assumed](./Arg-Anal-Method.qmd#example-should-i-lie-or-should-i-not), that there are only two options for you.
:::

::: {.callout-caution icon="false" collapse="true"}
### Step 1: [Identification fo Prima-Facie Reasons](arg-anal-pf-reasons-example.qmd)
Identify the list of all prima facie reasons in favour and against the available options for action.
:::

::: {.callout-caution icon="false" collapse="true"}
### Step 2: [Construction of Arguments](arg-anal-arg-constr.qmd)
Find or construct general principles which allow a [deductively valid inference]() from the premises (containing at least one prima facie reason) to a conclusion  (recommendation for one of the options for action).
:::

::: {.callout-caution icon="false" collapse="true"}
### Step 3: [Evaluation of Arguments]()
Discuss the premises of the reconstructed arguments with regard to their empirical validity and ethical plausibility.
:::

<!--
-------------
Linked sub-sides:

* [Trumping Arguments-internal-link](./Trumping-Principles.qmd) 

* [Balancing Arguments-internal](./Balancing-Principles.qmd)

* [Debunking Arguments]()

-->




