---
title: Step 2 - Construction of Arguments
---

::: {.callout-warning icon="false" collapse="true"}
# Theoretical Background

Construction of arguments is a creative task which involves several trial-and-error attempts. There is a formal requirement which a deductively valid construction must meet:

* find premises such that the respective prima facie reason is represented in at least one premise and that the respective conclusion deductively follows from all premises. 

* The formal requirement is necessary but not sufficient for an argument to be plausible: we can find a large number of principles which guarantee a deductively valid inference to a conclustion (in our case: one of the options for action). These principles differ, however, in their plausibility, as the exmaples below demonstrate.

:::

# Structure of Arguments

```{dot}
//| fig-cap: "Possible Arguments for Truth-Telling and Lying"
//| file: ./Graphics/arg-struct-lying-example.dot 
```

# Reconstructed Arguments

## Debunking Argumentation for Truth-Sticking

::: {.panel-tabset}

### Idea of the Arguments
This argumentation strategy is based on the idea that the prima facie reason for lying -- avoiding harm to your friend -- does not hold. 

### Map of the Arguments

```{dot}
//| fig-cap: "Argument map of debunking the prima facie reason for lying"
//| file: ./argument-rekos/method-example/pro-truth-debunking.ad.dot
```

### Reconstructed Arguments

The Debunking-Argumentation consists of two crucial steps:

1. An argument attacking the prima facie reasons supporting lying. In our case there is only one pro-lying reason "Avoidance of Harm". **A1: Debunking the prima facie reason for lying** attacks it.

2. The argument supporting the main claim ("Stick to Truth!"). It is reconstructed as **A2: There are no reasons against truth-sticking"**. 

::: {.callout-warning icon="false" collapse="true"}
# A1: Debunking the prima facie reason for lying

| | |
|:-:|:-------------------------|
|(1)|[**You cannot deceive your friend**]: Your friend reliably recognizes when you are not sincere to her. |
|(2)|If your friend recognizes that your recommendation for public transport is not sincere, she will not trust your advise.|
|(3)|If your friend does not trust your advise, it is not the case that by telling that the earlier connection is the last one you avoid for sure that your friend is significantly harmed.|
-----
| | |
|:-:|:-------------------------|
|(4)| [Conclusion]: It is not the case that by telling that the earlier connection is the last one you avoid for sure that your friend is significantly harmed.|
:::

::: {.callout-warning icon="false" collapse="true"}
# A2: There are no reasons against truth-sticking

| | |
|:-:|:-------------------------|
|(1)|There are only two options for action: sticking to truth or lying.|
|(2)|By telling the truth, you respect your friend's autonomy, satisfies her desires, avoid mistrust in your relationship, support a highly important social practice.|
|(3)|If you lie, there are no advantages.|
| |  <-- Premise (3) is justified by the Argument 1 |
|(4)|If there are only two options for action, and the one option realizes imporant benefits and the other none, the first option should be chosen. |
-----
| | |
|:-:|:-------------------------|
|(5)| [Conclusion]: You should stick to the truth.|
:::

:::

## Balancing Arguments for Truth-Sticking

If there are both prima facie reasons for truth-telling and for lying, the prima facie reasons must be weighed. An argument based on weighing pro- and contra considerations that supports truth-sticking must claim that the considerations pro truth-sticking outweigh the prima facie reason against it. There are two general strategies how such a weighing can be justified:

* **salient-concern argumentation**: by providing a salient principle for truth-sticking
* **consequentialist argumentation**: by taking the value of the consequences as the decisive consideration

### Salient-Concern Argumentation 

::::: {.panel-tabset}

#### Idea of the Arguments
This type of argumentation is based on the idea that particular [prima facie-reasons for truth-sticking](./arg-anal-pf-reasons-example.qmd) have such importance that they outweigh the expected harm from truth-sticking. The rationale of the arguments is that the expected harm is less significant for the friend is not deprived of the opportunity to avoid the harm. She is in certain sense responsible for its occurrence. 

#### Reconstructed Arguments

::: {.callout-warning icon="false" collapse="true"}
#### Autonomy-Argument

Situation S: the choice situation as [described here](./Arg-Anal-Method.qmd)

1. If you tell the truth in the situation S, it is reasonable to expect that your friend will be substantially harmed. 
2. If you lie in the situation S, you will infringe the autonomy of your friend.
3. If you tell the truth in the situation S, your friend will have the ability to avoid that she will be harmed.
4. If you have the ability to manipulate the behaviour of a person A such as to avoid that A will be harmed but A has the ability to avoid that she will be harmed without your manipulation as well, you ought to refrain from manipulating A's behaviour. 

----

5. **[Conclusion]**: You ought to refrain from lying.

:::

::: {.callout-warning icon="false" collapse="true"}
#### Desire-Fullfillment Argument

Situation S: the choice situation as [described here](./Arg-Anal-Method.qmd)

1. If you tell the truth in the situation S, it is reasonable to expect that your friend will be substantially harmed. 
2. If you lie in the situation S, you will be violating your friend's articulated desire.
3. If you tell the truth in the situation S, your friend will have the ability to avoid that she will be harmed.
4. If you have the ability to fulfil an articulated desire of your friend, the fulfilment of which may reasonably cause harm to your friend, but it is within your friend's power to avoid the harm from the fulfilemt of the desire, you ought to fulfil your friend's desire unless there are more other significant reasons against doing so.
5. There are no other significant reasons against your fulfilling your friend's desire. 

----

5. **[Conclusion]**: You ought to refrain from lying.

:::


::: {.callout-warning icon="false" collapse="true"}
#### Argument from Sincere Friendship

Situation S: the choice situation as [described here](./Arg-Anal-Method.qmd)

1. If you tell the truth in the situation S, you will fail to avoid for sure that your friend will be substantially harmed. 
3. If you tell the truth in the situation S, your friend will have the ability to avoid that she will be harmed.
2. If you lie in the situation S, you will create a precedent that you do not always behave as a practice of sincere friendship requires.
4. Maintaining the practice of sincere friendship with your friend is of such importance that you ought not to jeopardise the functioning of the practice by failing to avoid harm that is within your friend's power to avoid unless there are more important reasons for jeopardising your sincere friendship.
5. There are no more important reasons for jeopardising the friendship. 

----

5. **[Conclusion]**: You ought to refrain from lying.
:::


#### Map of the Arguments

```{=html}
<iframe src="./argument-rekos/method-example/pro-truth-balancing-autonomy-salient.html" width="100%" height="500px"></iframe>
```

:::::


### Consequentialist Argumentation

::::: {.panel-tabset}

#### Idea of the Arguments

Consequentialist arguments for truth-sticking argue that the consequences of truth-sticking are overall better than the consequences of lying. Since it is not possible to precisely forecast the consequences of the two options in our example, we have reconstructed two versions of the consequentialist argumenation based on weaker requirement on foreknowledge:

* the expected goodness-argument is based on the decision rule that the option should be realized whose consequences lead to the highest expected goodness. 
  * the main challenge of the proponents of this argument is to spell out how they account for the overall goodness of social states and how they know the probabilities of the possible outcomes.

* the uncertainty-argumentation aims to justify a choice for action in the light of uncertainty about the possible outcomes of truth-telling and lying. 
  * its main challenge lies in justifying a decision rule which specifies which option for action to choose based on merely possibilistic knowledge about the consequences. 


#### Reconstructed Arguments

::: {.callout-warning icon="false" collapse="true"}

#### Truth-Sticking Maximizes Expected Goodness

1. From the available options for action, the action ought to be chosen whose consequences lead to the highest expected good.
2. **[Calculation of the Expected Goodness]**: From the two available options for action, truth-telling and lying, the expected value from truth-telling is higher than the expected value from lying.
  * Premise (2) implies the claim: 
    * The expected badness of truth-telling -- which amounts to 
      * the probability that your friend will be harmed from truth-telling multiplied with the badness of the harm to her from missing the appointment 
    * is lower than the expected badness of lying which amounts to 
      * the badness of frustration of the desire of your friend plus the badness of disregard of her autonomy minus the probability that your friendship suffers from the lie multiplied with the goodness of your friendship minus the probability that the social practice of truth-telling suffers from your lie multiplied with the goodness of the practice.

----

3. **[Conclusion]**: You should tell your friend the truth about the traveling options for her.

* Premise (2) needs additional arguments justifying the calculation of the expected goodnes. 
  * the argument is depicted in the map as "Argumentation justifying the Pro-Truth-Aggregation": the argumentation needs to spell out how to account for goodness/badness of an outcomes; how to know the probability distribution of the possible outcomes; how to know the particular goodness/badness-value of the particular outcomes.

:::

::: {.callout-warning icon="false" collapse="true"}
#### Truth-Sticking under Uncertainty

1. The consequences of the two available options for action, truth-telling and lying, are uncertain, i.e. no probability distribution of their outcomes is known.
2. **[Evaluation under uncertaity]**: The worst possible outcomes of lying lead to much higher badness than the worst possible outcomes of truth-telling.
3. **[Decision Principle under Uncertainty]**: In a decision situation of uncertainty, the option for action should be chosen whose worst possible outcomes are the best.

----

4. **[Conclusion]**: You should tell your friend the truth about the traveling options for her.

* Premise (2) needs additional arguments justifying the evaluation of the worst possible outcomes.
  * the argument is depiceted in the map as "Argumentation justifying evaluation under uncertainty": the argumetation needs to spell out how to account for goodness/badness of possible outcomes and how to know the goodness/badness of the worst possible outcomes of the two options for action.
:::

#### Map of the Arguments

```{=html}
<iframe src="./argument-rekos/method-example/pro-truth-balancing-conseqent.html" width="100%" height="500px"></iframe>
```
:::::

<!--

| Pro Truth-Sticking (contra lying) | Pro Lying (contra truth-sticking) |
|:---------------------------------------------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Desire-Fulfillment** If it does not cause inappropriate costs to you, you should always fulfill the articulated desires of your friend, even if they can substantially harm your friend. | **Avoidance of Harm**  If it does not cause inappropriate costs to you, you should choose the action which minimizes the expected harm to your friend, even if you break established social norms thereby. |
| **Respecting Autonomy** If it does not cause inappropriate costs to you, you should always respect the autonomy of your friend, even if the respective actions can substantially harm your friend. |  |
| **Supporting a sincere relationship** If it does not cause inappropriate costs to you, you should always choose the action which preserves a sincere relationship with your friend, even if the respective actions can substantially harm your friend. | |
| **Supporting social practice** You should always tell the truth, even if the corresponding actions cause susbtantial harm to your friend. | |
: Trumping Principles {.striped}

| Maximizing Expected Value pro Lying |
|:-----|
| The expected harm for your friend from missing the meeting is higher than the harm to her caused by the unfulfilled desire, by the disregard of her autonomy, by the stress caused to your relationship, and by a violation of the social practice of honesty. |
: {.striped}

| Maximizing Expected Value pro Truth-Sticking |
|:-----|
| The expected harm for your friend from missing the meeting is lower  than the aggregated harm to her and to society which results from your friend's frustrated desire, disregard of her autonomy, the stress caused to your relationship, and a violation of the social practice of honesty. |
: {.striped}

| Precautionary Principle pro Truth-Sticking |
|:-----|
| XYz |
: {.striped}

| Precautionary Principle pro Lying |
|:-----|
| XYz |
: {.striped}
-->

## Debunking-Arguments for Lying {#sec-debunking-for-lying}
::::: {.panel-tabset}
### Idea of the Arguments
This argumentation strategy is based on the idea that the prima facie reasons for truth-telling do not hold.

### Map of the Arguments

```{=html}
<iframe src="./argument-rekos/method-example/pro-lying-debunking.html" width="100%" height="500px"></iframe>
```

### Reconstructed Arguments

The Debunking-Argumentation consists of two steps:

(@) An argument supporting the main claim ("You should lie!"). It is reconstructed as **A1: There are no reasons against lying"**. 

::: {.callout-warning icon="false" collapse="true"}
#### A1: There are no reasons against lying

1. There are only two options for action: sticking to truth or lying.
2. If you lie, you avoid that she is significantly harmed.
3. If you tell the truth, there are no morally significant advantages.
   * Premise (3) is justified by the Arguments (1)-(4)
4. If there are only two options for action, and the one option realizes imporant benefits and the other none, the first option should be chosen. 

-----

5. You should lie.
:::

(@) Arguments attacking the prima facie reasons for truth-telling. In our case there are four pro-truth-sticking reasons. A successful debunking argumentation requires arguments which attack each of the four prima faccie reasons for truth-sticking: 
  * A2: Debunking desire-fulfillment;
  * A3: Debunking respecting-autonomy;
  * A4: Debunking supporing-friendship;
  * A5: Debunking the claim that truth-telling supports an important social practice.

    As an example, we reconstruct the arguments A2 and A5. A2 is based on the claim that there is additional information which allows to interpret the desire of your friend to learn the last connection as another desire. Arguments A3 and A4 would need additional knowledge about peculiarities of the situation as well. 


::: {.callout-warning icon="false" collapse="true"}
#### A2: Debunking desire-fulfillment

1. Your friend has articulated the desire to learn when the last connection leaves by which she arrives at 2 o'clock at a meeting point. 
2. Very often, when your friend articulates the desire to learn the last connection for an important meeting, she has the desire to learn an earlier connection than the last one (for she knows that she often misses the last connection).
3. If a person articulates "p" and in most cases when a person articulates "p" she means "p-", it is reasonable to interpret the persons's articulation "p" as "p-".

----

4. It is reasonable to interpret your friend's articulated desire as desire to learn an earlier connection than the last one. 
5. If it is reasonable to interpret your friend's desire as q, then she has the desire that q.

----

6. Your friend has the desire to learn an earlier connection than the last one. 
:::

::: {.callout-warning icon="false" collapse="true"}
#### A3: Debunking the claim that truth-telling respects autonomy
not reconstructed here
:::

::: {.callout-warning icon="false" collapse="true"}
#### A4: Debunking the claim that truth-telling supports friendship
not reconstructed here
:::

::: {.callout-warning icon="false" collapse="true"}
#### A5: Debunking the claim that truth-telling supports an important social practice

1. The social practice of honesty/sincerity is maintained by billions of individual actions. 
2. If a practice is maintained by billions of individual actions, then a single act which violates the practice does not have any causal effect on the stability of the pratice. 

----

3. Telling the truth does not have a causal effect on the stability of the practice.

:::



:::::

## Balancing Arguments for Lying

If there are both prima facie reasons for truth-telling and for lying, the prima facie reasons must be weighed. An argument based on weighing pro- and contra considerations that supports lying must claim that the consideration pro lying outweigh the prima facie reasons against it. There are two general strategies how such a weighing can be justified:

* **salient-concern argumentation**: by providing a salient principle for lying
* **consequentialist argumentation**: by taking the value of the consequences as the decisive consideration

### Salient-Concern Argumentation

::::: {.panel-tabset}

### Idea of the Arguments
This argumentation is based on the idea that the [prima facie reason for lying](./arg-anal-pf-reasons-example.qmd) has such moral importance that it outweighs the prima facie reasons for truth-telling. The rationale of this reasoning is that substantial harm to a person should be avoided even if it requires violating other moral norms (which do not immediately cause harm).

### Map of Arguments
```{=html}
<iframe src="./argument-rekos/method-example/pro-lying-balancing-salient.html" width="100%" height="500px"></iframe>
```

### Reconstructed Argument
::: {.callout-warning icon="false" collapse="true"}
#### Avoiding-Harm Argument
Situation S: the choice situation as [described here](./Arg-Anal-Method.qmd)

1. If you tell the truth in the situation S, it is reasonable to expect that your friend will be substantially harmed. 
2. If you have the ability to manipulate the behaviour of a person A such as to avoid that A will be harmed, you ought to manipulate A's behaviour even if you violate further moral principles whithout causing additional harm.
3. If you lie in the situation S, you will violate moral principles without causing additional harm. 

----

4. **[Conclusion]**: You ought to lie in S.

:::
:::::

## Consequentialist Argumentation for Lying

::::: {.panel-tabset}

### Idea of the Arguments

Consequentialist arguments for lying argue that the consequences of lying in the particular situation are overall better than the consequences of truth-sticking in this situation. Since it is not possible to precisely forecast the consequences of the two options in our example, we have reconstructed two versions of the consequentialist argumenation based on weaker requirement on foreknowledge:

* the expected goodness-argument is based on the decision rule that the option should be realized whose consequences lead to the highest expected goodness. 
  * the main challenge of the proponents of this argument is to spell out how they account for the overall goodness of social states and how they know the probabilities of the possible outcomes.

* the uncertainty-argumentation aims to justify a choice for action in the light of uncertainty about the possible outcomes of truth-telling and lying. 
  * its main challenge lies in justifying a decision rule which specifies which option for action to choose based on merely possibilistic knowledge about the consequences. 


### Reconstructed Arguments

::: {.callout-warning icon="false" collapse="true"}
#### Lying Maximizes Expected Goodness

1. From the available options for action, the action ought to be chosen whose consequences lead to the highest expected good.
2. **[Calculation of the Expected Goodness]**: From the two available options for action, truth-telling and lying, the expected value from lying is higher than the expected value from sticking to truth.

----

3. **[Conclusion]**: You should lie in the Situation S.

* Premise (2) implies the claim: 
    * The expected badness of truth-telling -- which amounts to 
      * the probability that your friend will be harmed from truth-telling multiplied with the badness of the harm to her from missing the appointment 
    * is higher than the expected badness of lying which amounts to 
      * the badness of frustration of the desire of your friend plus the badness of disregard of her autonomy minus the probability that your friendship suffers from the lie multiplied with the goodness of your friendship minus the probability that the social practice of truth-telling suffers from your lie multiplied with the goodness of the practice.

* Premise (2) needs additional arguments justifying the calculation of the expected goodnes. 
  * the argument is depicted in the map as "Argumentation justifying the Pro-Lying-Aggregation": the argumentation needs to spell out how to account for goodness/badness of an outcomes; how to know the probability distribution of the possible outcomes; how to know the particular goodness/badness-value of the particular outcomes.
:::

::: {.callout-warning icon="false" collapse="true"}
#### Lying under Uncertainty

1. The consequences of the two available options for action, truth-telling and lying, are uncertain, i.e. no probability distribution of their outcomes is known.
2. **[Evaluation under uncertaity]**: The worst possible outcomes of sticking to truth are much worse than the worst possible outcomes of lying.
3. **[Decision Principle under Uncertainty]**: In a decision situation of uncertainty, the option for action should be chosen whose worst possible outcomes are the best.

----

4. **[Conclusion]**: You should lie in situation S.

* Premise (2) needs additional arguments justifying the evaluation of the worst possible outcomes.
  * the argument is depiceted in the map as "Argumentation justifying evaluation under uncertainty": the argumetation needs to spell out how to account for goodness/badness of possible outcomes and how to know the goodness/badness of the worst possible outcomes of the two options for action.
:::

### Map of Arguments

```{=html}
<iframe src="./argument-rekos/method-example/pro-lying-balancing-consequent.html" width="100%" height="500px"></iframe>
```

:::::